statafolder: C:\Program Files\Stata18
edition: mp  # one of se, be or mp
display_splash: False  #whether to start STATA main screen upon init

maxcores: None
buffer: 1 # number of cores to save from multiprocessing

